version: 2.1
orbs:
  slack: circleci/slack@3.4.2
 
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "894d773415ebed996164cf4873186111ce2923da" #上記メモったハッシュを指定
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/var/www/adachin.me/deploy.sh"
      - slack/status:
          fail_only: true
          mentions: 'here'
          failure_message: 'Error Deploy 🚨 \n :innocent: ${CIRCLE_USERNAME}    :branch: ${CIRCLE_BRANCH}'
          webhook: ${SLACK_WEBHOOK}
      - slack/notify:
          title: 👍
          color: '#42f486'
          message: ' Deploy OK ✨ \n :grin: ${CIRCLE_USERNAME}    :branch: ${CIRCLE_BRANCH}'
 
workflows:
  version: 2.1
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master